apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: custom-test-availability-ratio
  labels:
    service_name: custom
    feature_name: test
    slo_name: availability-ratio
spec:
  description: 99.99% of fake requests to custom backends are valid
  backend: samples.custom.custom_backend.CustomBackend
  method: good_bad_ratio
  exporters:
  - samples.custom.custom_exporter.CustomMetricExporter
  - samples.custom.custom_exporter.CustomSLOExporter
  service_level_indicator: {}
  goal: 0.999
