apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: pubsub-subscription-throughput
  labels:
    service_name: pubsub
    feature_name: subscription
    slo_name: throughput
spec:
  description: Throughput of Pub/Sub subscription
  backend: cloud_monitoring_mql
  method: good_bad_ratio
  exporters:
  - cloud_monitoring
  service_level_indicator:
    filter_good: >
      fetch 'pubsub_subscription'
      | metric 'pubsub.googleapis.com/subscription/ack_message_count'
      | filter resource.project_id == '${PUBSUB_PROJECT_ID}'
    filter_bad: >
      fetch 'pubsub_subscription'
      | metric 'pubsub.googleapis.com/subscription/num_outstanding_messages'
      | filter resource.project_id == '${PUBSUB_PROJECT_ID}'
  goal: 0.95
